title: I Am L-Hyun
email: dkh1001@outlook.kr
author: L-Hyun
copyright: Copyright © 1970-2010
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: ""
url: "https://l-hyun.github.io/"
favicon: ""

yat:
  date_format: "%b %d, %Y"

markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
