title: I'm L-Hyun
author: L-Hyun
email: dkh1001@outlook.kr
description: > # this means to ignore newlines until "show_exerpts:"
  L-Hyun's CS Blog
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Lee Seok-Hyun
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  L-Hyun
    linkedIn: in/seok-hyun-lee-0705b317b/
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed