title: I'm L-Hyun
author: L-Hyun
email: dkh1001@outlook.kr
description: This is L-Hyun. I'm just a developer
show_excerpts: true
baseurl: ""

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: I Am L-Hyun
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  social_links:
    twitter: thelehhman
    github: thelehhman
    linkedIn: in/thelehhman
    rss: rss

plugins:
  - jekyll-seo-tag
