title: I Am L-Hyun
email: dkh1001@outlook.kr
author: L-Hyun
copyright: Copyright © 1970-2010
description: L-Hyun's Logging Blog

baseurl: ""
url: "https://l-hyun.github.io/"
favicon: ""

yat:
  date_format: "%b %d, %Y"

markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
